import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { LogoutButton } from "./components/LogoutButton";
import { authOptions } from "@/lib/auth";
import SessionWrapper from "./components/SessionWrapper";

export const metadata: Metadata = {
  title: "Simple Authenication",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  console.log("Current Session:", session); //
  return (
    <html lang="en">
      <SessionWrapper>
        <body>
          <nav style={{ padding: 10, borderBottom: "1px solid #ccc" }}>
            {session && (
              <>
                <span>{session.user?.email}</span>
                <LogoutButton />
              </>
            )}
          </nav>

          {children}
        </body>
      </SessionWrapper>
    </html>
  );
}
