import type { Metadata } from "next";
//import SessionWrapper from "./components/SessionWrapper";
import NavBar from "./components/Navbar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { LogoutButton } from "./components/LogoutButton";
import "./globals.css";

export const metadata: Metadata = {
  title: "Simple Authenication",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      {/* <SessionWrapper> */}
      <body>
        {/* <NavBar /> */}
        <nav style={{ padding: 10, borderBottom: "1px solid #ccc" }}>
          {session && (
            <>
              <span>{session.user?.email}</span>
              <LogoutButton />
            </>
          )}
        </nav>
        <main>{children}</main>
      </body>
      {/* </SessionWrapper> */}
    </html>
  );
}
