import type { Metadata } from "next";
import SessionWrapper from "./components/SessionWrapper";
import NavBar from "./components/Navbar";
export const metadata: Metadata = {
  title: "Simple Authenication",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <SessionWrapper>
        <body>
          <NavBar />
          {children}
        </body>
      </SessionWrapper>
    </html>
  );
}
